#ifndef STRUCT_TYPE_ALL_H
#define STRUCT_TYPE_ALL_H

#include <mpi.h>


    MPI_datatype MPI_COLOR_STRUCT,
    MPI_VECTOR_STRUCT,

    MPI_CAMERA_STRUCT,
    MPI_SCREEN_STRUCT,
    MPI_SCENE_STRUCT,

    MPI_MATERIAL_STRUCT,
    MPI_SPHERE_STRUCT;


#endif